//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.225
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChameleonCoder {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizer() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChameleonCoder.Localizer", typeof(Localizer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die attach the {0} ähnelt.
        /// </summary>
        internal static string Action_Attach {
            get {
                return ResourceManager.GetString("Action_Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die link the {0} to a {1} ähnelt.
        /// </summary>
        internal static string Action_Link {
            get {
                return ResourceManager.GetString("Action_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die new {0} ähnelt.
        /// </summary>
        internal static string Action_NewFile {
            get {
                return ResourceManager.GetString("Action_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die new {0} ähnelt.
        /// </summary>
        internal static string Action_NewLibrary {
            get {
                return ResourceManager.GetString("Action_NewLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die new {0} ähnelt.
        /// </summary>
        internal static string Action_NewProject {
            get {
                return ResourceManager.GetString("Action_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die new {0} ähnelt.
        /// </summary>
        internal static string Action_NewTask {
            get {
                return ResourceManager.GetString("Action_NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die about... ähnelt.
        /// </summary>
        internal static string Item_About {
            get {
                return ResourceManager.GetString("Item_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die options ähnelt.
        /// </summary>
        internal static string Item_Options {
            get {
                return ResourceManager.GetString("Item_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die code file ähnelt.
        /// </summary>
        internal static string ResourceType_Code {
            get {
                return ResourceManager.GetString("ResourceType_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die file ähnelt.
        /// </summary>
        internal static string ResourceType_File {
            get {
                return ResourceManager.GetString("ResourceType_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die library ähnelt.
        /// </summary>
        internal static string ResourceType_Library {
            get {
                return ResourceManager.GetString("ResourceType_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die project ähnelt.
        /// </summary>
        internal static string ResourceType_Project {
            get {
                return ResourceManager.GetString("ResourceType_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die resource ähnelt.
        /// </summary>
        internal static string ResourceType_Resource {
            get {
                return ResourceManager.GetString("ResourceType_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die task ähnelt.
        /// </summary>
        internal static string ResourceType_Task {
            get {
                return ResourceManager.GetString("ResourceType_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die maul.esel ähnelt.
        /// </summary>
        internal static string Translator {
            get {
                return ResourceManager.GetString("Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die help ähnelt.
        /// </summary>
        internal static string traymenu1 {
            get {
                return ResourceManager.GetString("traymenu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die reload ähnelt.
        /// </summary>
        internal static string traymenu2 {
            get {
                return ResourceManager.GetString("traymenu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die exit ähnelt.
        /// </summary>
        internal static string traymenu3 {
            get {
                return ResourceManager.GetString("traymenu3", resourceCulture);
            }
        }
    }
}
