//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.237
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChameleonCoder.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChameleonCoder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        internal static string Action_Add {
            get {
                return ResourceManager.GetString("Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        internal static string Action_Apply {
            get {
                return ResourceManager.GetString("Action_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string Action_Exit {
            get {
                return ResourceManager.GetString("Action_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string Action_OK {
            get {
                return ResourceManager.GetString("Action_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        internal static string Action_Remove {
            get {
                return ResourceManager.GetString("Action_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart ähnelt.
        /// </summary>
        internal static string Action_Restart {
            get {
                return ResourceManager.GetString("Action_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ChameleonCoder (original author: {0}) ähnelt.
        /// </summary>
        internal static string AutoTemplate_Author {
            get {
                return ResourceManager.GetString("AutoTemplate_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die new empty &quot;{0}&quot; resource ähnelt.
        /// </summary>
        internal static string AutoTemplate_Description {
            get {
                return ResourceManager.GetString("AutoTemplate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete the {0}-resource and all its child resources? ähnelt.
        /// </summary>
        internal static string Del_Confirm {
            get {
                return ResourceManager.GetString("Del_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        internal static string Edit_Copy {
            get {
                return ResourceManager.GetString("Edit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cut ähnelt.
        /// </summary>
        internal static string Edit_Cut {
            get {
                return ResourceManager.GetString("Edit_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die new element... ähnelt.
        /// </summary>
        internal static string Edit_NewCodeStub {
            get {
                return ResourceManager.GetString("Edit_NewCodeStub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste ähnelt.
        /// </summary>
        internal static string Edit_Paste {
            get {
                return ResourceManager.GetString("Edit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Redo ähnelt.
        /// </summary>
        internal static string Edit_Redo {
            get {
                return ResourceManager.GetString("Edit_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace ähnelt.
        /// </summary>
        internal static string Edit_Replace {
            get {
                return ResourceManager.GetString("Edit_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string Edit_Save {
            get {
                return ResourceManager.GetString("Edit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        internal static string Edit_Search {
            get {
                return ResourceManager.GetString("Edit_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo ähnelt.
        /// </summary>
        internal static string Edit_Undo {
            get {
                return ResourceManager.GetString("Edit_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom in ähnelt.
        /// </summary>
        internal static string Edit_ZoomIn {
            get {
                return ResourceManager.GetString("Edit_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom out ähnelt.
        /// </summary>
        internal static string Edit_ZoomOut {
            get {
                return ResourceManager.GetString("Edit_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The assembly at &quot;{0}&quot; does not contain ChameleonCoder plugins that aren&apos;t already installed. ähnelt.
        /// </summary>
        internal static string Error_InstallEmptyAssembly {
            get {
                return ResourceManager.GetString("Error_InstallEmptyAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file &quot;{0}&quot; is not a valid assembly. ähnelt.
        /// </summary>
        internal static string Error_InstallNoAssembly {
            get {
                return ResourceManager.GetString("Error_InstallNoAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The assembly at &quot;{0}&quot; is not a ChameleonCoder plugin assembly. ähnelt.
        /// </summary>
        internal static string Error_InstallNoPlugin {
            get {
                return ResourceManager.GetString("Error_InstallNoPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file &quot;{0}&quot; could not be opened.
        ///ChameleonCoder will close. ähnelt.
        /// </summary>
        internal static string Error_InvalidFile {
            get {
                return ResourceManager.GetString("Error_InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The resource &quot;{0}&quot; could not be moved to resource &quot;{1}&quot;:
        ///resources cannot be moved to descendants. ähnelt.
        /// </summary>
        internal static string Error_MoveToDescendant {
            get {
                return ResourceManager.GetString("Error_MoveToDescendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured during packaging: ähnelt.
        /// </summary>
        internal static string Error_Package {
            get {
                return ResourceManager.GetString("Error_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CC resource file ähnelt.
        /// </summary>
        internal static string Ext_CCR {
            get {
                return ResourceManager.GetString("Ext_CCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XML Alias: ähnelt.
        /// </summary>
        internal static string Info_Alias {
            get {
                return ResourceManager.GetString("Info_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin Name (Assembly): ähnelt.
        /// </summary>
        internal static string Info_Assembly {
            get {
                return ResourceManager.GetString("Info_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Author: ähnelt.
        /// </summary>
        internal static string Info_Author {
            get {
                return ResourceManager.GetString("Info_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Class: ähnelt.
        /// </summary>
        internal static string Info_Class {
            get {
                return ResourceManager.GetString("Info_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die compatible languages: ähnelt.
        /// </summary>
        internal static string Info_CompatibleLanguages {
            get {
                return ResourceManager.GetString("Info_CompatibleLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die compiled Path: ähnelt.
        /// </summary>
        internal static string Info_CompilationPath {
            get {
                return ResourceManager.GetString("Info_CompilationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description: ähnelt.
        /// </summary>
        internal static string Info_Description {
            get {
                return ResourceManager.GetString("Info_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin file: ähnelt.
        /// </summary>
        internal static string Info_File {
            get {
                return ResourceManager.GetString("Info_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path: ähnelt.
        /// </summary>
        internal static string Info_FSPath {
            get {
                return ResourceManager.GetString("Info_FSPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icon: ähnelt.
        /// </summary>
        internal static string Info_Icon {
            get {
                return ResourceManager.GetString("Info_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Identifier: ähnelt.
        /// </summary>
        internal static string Info_Identifier {
            get {
                return ResourceManager.GetString("Info_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language: ähnelt.
        /// </summary>
        internal static string Info_Language {
            get {
                return ResourceManager.GetString("Info_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string Info_Name {
            get {
                return ResourceManager.GetString("Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parent: ähnelt.
        /// </summary>
        internal static string Info_Parent {
            get {
                return ResourceManager.GetString("Info_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die special information: ähnelt.
        /// </summary>
        internal static string Info_Special {
            get {
                return ResourceManager.GetString("Info_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version: ähnelt.
        /// </summary>
        internal static string Info_Version {
            get {
                return ResourceManager.GetString("Info_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icon &amp; Color: ähnelt.
        /// </summary>
        internal static string Info_Visual {
            get {
                return ResourceManager.GetString("Info_Visual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        internal static string Item_Home {
            get {
                return ResourceManager.GetString("Item_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resources ähnelt.
        /// </summary>
        internal static string Item_List {
            get {
                return ResourceManager.GetString("Item_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugins ähnelt.
        /// </summary>
        internal static string Item_Plugins {
            get {
                return ResourceManager.GetString("Item_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} [editing] ähnelt.
        /// </summary>
        internal static string Item_ResourceEdit {
            get {
                return ResourceManager.GetString("Item_ResourceEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ähnelt.
        /// </summary>
        internal static string Item_ResourceView {
            get {
                return ResourceManager.GetString("Item_ResourceView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Item_Settings {
            get {
                return ResourceManager.GetString("Item_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable grouping ähnelt.
        /// </summary>
        internal static string List_EnableGroups {
            get {
                return ResourceManager.GetString("List_EnableGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hidden resource types ähnelt.
        /// </summary>
        internal static string List_HiddenTypes {
            get {
                return ResourceManager.GetString("List_HiddenTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort resources ähnelt.
        /// </summary>
        internal static string List_SortResources {
            get {
                return ResourceManager.GetString("List_SortResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add metadata ähnelt.
        /// </summary>
        internal static string Meta_Add {
            get {
                return ResourceManager.GetString("Meta_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die delete selected metadata ähnelt.
        /// </summary>
        internal static string Meta_Delete {
            get {
                return ResourceManager.GetString("Meta_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the new metadata&apos;s name: ähnelt.
        /// </summary>
        internal static string Meta_EnterName {
            get {
                return ResourceManager.GetString("Meta_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die metadata key ähnelt.
        /// </summary>
        internal static string Meta_Key {
            get {
                return ResourceManager.GetString("Meta_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die value ähnelt.
        /// </summary>
        internal static string Meta_Value {
            get {
                return ResourceManager.GetString("Meta_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} module (version {1}) by {2} ähnelt.
        /// </summary>
        internal static string ModuleInfo {
            get {
                return ResourceManager.GetString("ModuleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resources were successfully packaged! ähnelt.
        /// </summary>
        internal static string Pack_Finished {
            get {
                return ResourceManager.GetString("Pack_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to include the file system equivalents for the packaged resources? ähnelt.
        /// </summary>
        internal static string Pack_IncludeFS {
            get {
                return ResourceManager.GetString("Pack_IncludeFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to include the target resources for the packaged resources? ähnelt.
        /// </summary>
        internal static string Pack_IncludeResolve {
            get {
                return ResourceManager.GetString("Pack_IncludeResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die all plugins ähnelt.
        /// </summary>
        internal static string Plugin_All {
            get {
                return ResourceManager.GetString("Plugin_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die components ähnelt.
        /// </summary>
        internal static string Plugin_ComponentFactory {
            get {
                return ResourceManager.GetString("Plugin_ComponentFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die install plugins ähnelt.
        /// </summary>
        internal static string Plugin_Install {
            get {
                return ResourceManager.GetString("Plugin_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die install all ähnelt.
        /// </summary>
        internal static string Plugin_InstallAll {
            get {
                return ResourceManager.GetString("Plugin_InstallAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die install selected plugins ähnelt.
        /// </summary>
        internal static string Plugin_InstallSelected {
            get {
                return ResourceManager.GetString("Plugin_InstallSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die language modules ähnelt.
        /// </summary>
        internal static string Plugin_LanguageModule {
            get {
                return ResourceManager.GetString("Plugin_LanguageModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die services ähnelt.
        /// </summary>
        internal static string Plugin_Service {
            get {
                return ResourceManager.GetString("Plugin_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die templates ähnelt.
        /// </summary>
        internal static string Plugin_Template {
            get {
                return ResourceManager.GetString("Plugin_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die uninstall selected plugin ähnelt.
        /// </summary>
        internal static string Plugin_Uninstall {
            get {
                return ResourceManager.GetString("Plugin_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        internal static string PropertyGroup_General {
            get {
                return ResourceManager.GetString("PropertyGroup_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Editing ähnelt.
        /// </summary>
        internal static string RibbonContext_Edit {
            get {
                return ResourceManager.GetString("RibbonContext_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View Utilities ähnelt.
        /// </summary>
        internal static string RibbonContext_List {
            get {
                return ResourceManager.GetString("RibbonContext_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resource ähnelt.
        /// </summary>
        internal static string RibbonContext_View {
            get {
                return ResourceManager.GetString("RibbonContext_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clipboard ähnelt.
        /// </summary>
        internal static string RibbonGroup_Clipboard {
            get {
                return ResourceManager.GetString("RibbonGroup_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Code ähnelt.
        /// </summary>
        internal static string RibbonGroup_Code {
            get {
                return ResourceManager.GetString("RibbonGroup_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string RibbonGroup_SaveOpen {
            get {
                return ResourceManager.GetString("RibbonGroup_SaveOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search &amp; Replace ähnelt.
        /// </summary>
        internal static string RibbonGroup_Search {
            get {
                return ResourceManager.GetString("RibbonGroup_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo &amp; Redo ähnelt.
        /// </summary>
        internal static string RibbonGroup_UndoRedo {
            get {
                return ResourceManager.GetString("RibbonGroup_UndoRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View ähnelt.
        /// </summary>
        internal static string RibbonGroup_View {
            get {
                return ResourceManager.GetString("RibbonGroup_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die create a new resource ähnelt.
        /// </summary>
        internal static string Selection_CreateNew {
            get {
                return ResourceManager.GetString("Selection_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die go to resource list ähnelt.
        /// </summary>
        internal static string Selection_List {
            get {
                return ResourceManager.GetString("Selection_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die view plugins ähnelt.
        /// </summary>
        internal static string Selection_Plugins {
            get {
                return ResourceManager.GetString("Selection_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die change the configuration ähnelt.
        /// </summary>
        internal static string Selection_Settings {
            get {
                return ResourceManager.GetString("Selection_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die running service: {0}... ähnelt.
        /// </summary>
        internal static string ServiceInfo {
            get {
                return ResourceManager.GetString("ServiceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Services ähnelt.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die code font: ähnelt.
        /// </summary>
        internal static string Setting_CodeFont {
            get {
                return ResourceManager.GetString("Setting_CodeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die code font size: ähnelt.
        /// </summary>
        internal static string Setting_CodeFontSize {
            get {
                return ResourceManager.GetString("Setting_CodeFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable updates ähnelt.
        /// </summary>
        internal static string Setting_EnableUpdate {
            get {
                return ResourceManager.GetString("Setting_EnableUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die install COM support ähnelt.
        /// </summary>
        internal static string Setting_InstallCOM {
            get {
                return ResourceManager.GetString("Setting_InstallCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die install file extensions ähnelt.
        /// </summary>
        internal static string Setting_InstallExt {
            get {
                return ResourceManager.GetString("Setting_InstallExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language: ähnelt.
        /// </summary>
        internal static string Setting_Language {
            get {
                return ResourceManager.GetString("Setting_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die select directory ähnelt.
        /// </summary>
        internal static string Setting_SelectProgDir {
            get {
                return ResourceManager.GetString("Setting_SelectProgDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How do you want to start? ähnelt.
        /// </summary>
        internal static string StartSelection {
            get {
                return ResourceManager.GetString("StartSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CC - creating new metadata... ähnelt.
        /// </summary>
        internal static string Status_CreateMeta {
            get {
                return ResourceManager.GetString("Status_CreateMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CC - deleting resources... ähnelt.
        /// </summary>
        internal static string Status_DeleteResource {
            get {
                return ResourceManager.GetString("Status_DeleteResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CC - installing plugins... ähnelt.
        /// </summary>
        internal static string Status_InstallPlugin {
            get {
                return ResourceManager.GetString("Status_InstallPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CC - Moving resource... ähnelt.
        /// </summary>
        internal static string Status_Move {
            get {
                return ResourceManager.GetString("Status_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CC - packaging resources... ähnelt.
        /// </summary>
        internal static string Status_Pack {
            get {
                return ResourceManager.GetString("Status_Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select this resource type ähnelt.
        /// </summary>
        internal static string TypeSelector_Select {
            get {
                return ResourceManager.GetString("TypeSelector_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add a child resource ähnelt.
        /// </summary>
        internal static string View_AddChild {
            get {
                return ResourceManager.GetString("View_AddChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        internal static string View_Copy {
            get {
                return ResourceManager.GetString("View_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string View_Delete {
            get {
                return ResourceManager.GetString("View_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string View_Edit {
            get {
                return ResourceManager.GetString("View_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move ähnelt.
        /// </summary>
        internal static string View_Move {
            get {
                return ResourceManager.GetString("View_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome! ähnelt.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
