//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChameleonCoder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChameleonCoder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Action_Add {
            get {
                return ResourceManager.GetString("Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Action_Exit {
            get {
                return ResourceManager.GetString("Action_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Action_OK {
            get {
                return ResourceManager.GetString("Action_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Action_Remove {
            get {
                return ResourceManager.GetString("Action_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Action_Restart {
            get {
                return ResourceManager.GetString("Action_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChameleonCoder (original author: {0}).
        /// </summary>
        internal static string AutoTemplate_Author {
            get {
                return ResourceManager.GetString("AutoTemplate_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new empty &quot;{0}&quot; resource.
        /// </summary>
        internal static string AutoTemplate_Description {
            get {
                return ResourceManager.GetString("AutoTemplate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the {0}-resource and all its child resources?.
        /// </summary>
        internal static string Del_Confirm {
            get {
                return ResourceManager.GetString("Del_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Edit_Copy {
            get {
                return ResourceManager.GetString("Edit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Edit_Cut {
            get {
                return ResourceManager.GetString("Edit_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new element....
        /// </summary>
        internal static string Edit_NewCodeStub {
            get {
                return ResourceManager.GetString("Edit_NewCodeStub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Edit_Paste {
            get {
                return ResourceManager.GetString("Edit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Edit_Redo {
            get {
                return ResourceManager.GetString("Edit_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string Edit_Replace {
            get {
                return ResourceManager.GetString("Edit_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Edit_Save {
            get {
                return ResourceManager.GetString("Edit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Edit_Search {
            get {
                return ResourceManager.GetString("Edit_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Edit_Undo {
            get {
                return ResourceManager.GetString("Edit_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        internal static string Edit_ZoomIn {
            get {
                return ResourceManager.GetString("Edit_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        internal static string Edit_ZoomOut {
            get {
                return ResourceManager.GetString("Edit_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file &quot;{0}&quot; is already loaded. You cannot open or replace it..
        /// </summary>
        internal static string Error_FileAlreadyLoaded {
            get {
                return ResourceManager.GetString("Error_FileAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly at &quot;{0}&quot; does not contain ChameleonCoder plugins that aren&apos;t already installed..
        /// </summary>
        internal static string Error_InstallEmptyAssembly {
            get {
                return ResourceManager.GetString("Error_InstallEmptyAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; is not a valid assembly..
        /// </summary>
        internal static string Error_InstallNoAssembly {
            get {
                return ResourceManager.GetString("Error_InstallNoAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly at &quot;{0}&quot; is not a ChameleonCoder plugin assembly..
        /// </summary>
        internal static string Error_InstallNoPlugin {
            get {
                return ResourceManager.GetString("Error_InstallNoPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; could not be opened..
        /// </summary>
        internal static string Error_InvalidFile {
            get {
                return ResourceManager.GetString("Error_InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name you entered is already used by metadata..
        /// </summary>
        internal static string Error_MetaDuplicateName {
            get {
                return ResourceManager.GetString("Error_MetaDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not enter a valid name for the metadata..
        /// </summary>
        internal static string Error_MetaInvalidName {
            get {
                return ResourceManager.GetString("Error_MetaInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource &quot;{0}&quot; could not be moved to resource &quot;{1}&quot;:
        ///resources cannot be moved to descendants..
        /// </summary>
        internal static string Error_MoveToDescendant {
            get {
                return ResourceManager.GetString("Error_MoveToDescendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected directory &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string Error_NonExistentDir {
            get {
                return ResourceManager.GetString("Error_NonExistentDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC resource file.
        /// </summary>
        internal static string Ext_CCR {
            get {
                return ResourceManager.GetString("Ext_CCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close all opened files?.
        /// </summary>
        internal static string File_ConfirmClose {
            get {
                return ResourceManager.GetString("File_ConfirmClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to overwrite the file at &quot;{0}&quot;?.
        /// </summary>
        internal static string File_ConfirmOverwrite {
            get {
                return ResourceManager.GetString("File_ConfirmOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new file&apos;s name:.
        /// </summary>
        internal static string File_EnterName {
            get {
                return ResourceManager.GetString("File_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the path to the file to create..
        /// </summary>
        internal static string File_SelectCreate {
            get {
                return ResourceManager.GetString("File_SelectCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file you want to open..
        /// </summary>
        internal static string File_SelectOpen {
            get {
                return ResourceManager.GetString("File_SelectOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        internal static string Info_Author {
            get {
                return ResourceManager.GetString("Info_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compatible languages:.
        /// </summary>
        internal static string Info_CompatibleLanguages {
            get {
                return ResourceManager.GetString("Info_CompatibleLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compiled Path:.
        /// </summary>
        internal static string Info_CompilationPath {
            get {
                return ResourceManager.GetString("Info_CompilationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Info_Description {
            get {
                return ResourceManager.GetString("Info_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        internal static string Info_FSPath {
            get {
                return ResourceManager.GetString("Info_FSPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon:.
        /// </summary>
        internal static string Info_Icon {
            get {
                return ResourceManager.GetString("Info_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier:.
        /// </summary>
        internal static string Info_Identifier {
            get {
                return ResourceManager.GetString("Info_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Info_Language {
            get {
                return ResourceManager.GetString("Info_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Info_Name {
            get {
                return ResourceManager.GetString("Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent:.
        /// </summary>
        internal static string Info_Parent {
            get {
                return ResourceManager.GetString("Info_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to special information:.
        /// </summary>
        internal static string Info_Special {
            get {
                return ResourceManager.GetString("Info_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Info_Version {
            get {
                return ResourceManager.GetString("Info_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file management.
        /// </summary>
        internal static string Item_FileManagement {
            get {
                return ResourceManager.GetString("Item_FileManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Item_Home {
            get {
                return ResourceManager.GetString("Item_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string Item_List {
            get {
                return ResourceManager.GetString("Item_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        internal static string Item_Plugins {
            get {
                return ResourceManager.GetString("Item_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [editing].
        /// </summary>
        internal static string Item_ResourceEdit {
            get {
                return ResourceManager.GetString("Item_ResourceEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string Item_ResourceView {
            get {
                return ResourceManager.GetString("Item_ResourceView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Item_Settings {
            get {
                return ResourceManager.GetString("Item_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable grouping.
        /// </summary>
        internal static string List_EnableGroups {
            get {
                return ResourceManager.GetString("List_EnableGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden resource types.
        /// </summary>
        internal static string List_HiddenTypes {
            get {
                return ResourceManager.GetString("List_HiddenTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort resources.
        /// </summary>
        internal static string List_SortResources {
            get {
                return ResourceManager.GetString("List_SortResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add metadata.
        /// </summary>
        internal static string Meta_Add {
            get {
                return ResourceManager.GetString("Meta_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete selected metadata.
        /// </summary>
        internal static string Meta_Delete {
            get {
                return ResourceManager.GetString("Meta_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new metadata&apos;s name:.
        /// </summary>
        internal static string Meta_EnterName {
            get {
                return ResourceManager.GetString("Meta_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metadata key.
        /// </summary>
        internal static string MetadataKey {
            get {
                return ResourceManager.GetString("MetadataKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string MetadataValue {
            get {
                return ResourceManager.GetString("MetadataValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} module (version {1}) by {2}.
        /// </summary>
        internal static string ModuleInfo {
            get {
                return ResourceManager.GetString("ModuleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to install all.
        /// </summary>
        internal static string PI_InstallAll {
            get {
                return ResourceManager.GetString("PI_InstallAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to install selected plugins.
        /// </summary>
        internal static string PI_InstallSelected {
            get {
                return ResourceManager.GetString("PI_InstallSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the plugin you want to install..
        /// </summary>
        internal static string Plugin_SelectInstall {
            get {
                return ResourceManager.GetString("Plugin_SelectInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to install plugins.
        /// </summary>
        internal static string PP_Install {
            get {
                return ResourceManager.GetString("PP_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all plugins.
        /// </summary>
        internal static string PP_TypesAll {
            get {
                return ResourceManager.GetString("PP_TypesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language modules.
        /// </summary>
        internal static string PP_TypesLanguageModule {
            get {
                return ResourceManager.GetString("PP_TypesLanguageModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resource types.
        /// </summary>
        internal static string PP_TypesResourceFactory {
            get {
                return ResourceManager.GetString("PP_TypesResourceFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RichContent types.
        /// </summary>
        internal static string PP_TypesRichContentFactory {
            get {
                return ResourceManager.GetString("PP_TypesRichContentFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to services.
        /// </summary>
        internal static string PP_TypesService {
            get {
                return ResourceManager.GetString("PP_TypesService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to templates.
        /// </summary>
        internal static string PP_TypesTemplate {
            get {
                return ResourceManager.GetString("PP_TypesTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uninstall selected plugin.
        /// </summary>
        internal static string PP_Uninstall {
            get {
                return ResourceManager.GetString("PP_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string PropertyGroup_General {
            get {
                return ResourceManager.GetString("PropertyGroup_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add directory reference.
        /// </summary>
        internal static string Ref_AddDirRef {
            get {
                return ResourceManager.GetString("Ref_AddDirRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add file reference.
        /// </summary>
        internal static string Ref_AddFileRef {
            get {
                return ResourceManager.GetString("Ref_AddFileRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add resource reference.
        /// </summary>
        internal static string Ref_AddResRef {
            get {
                return ResourceManager.GetString("Ref_AddResRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete reference.
        /// </summary>
        internal static string Ref_Delete {
            get {
                return ResourceManager.GetString("Ref_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the reference target..
        /// </summary>
        internal static string Ref_SelectTarget {
            get {
                return ResourceManager.GetString("Ref_SelectTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        internal static string RibbonContext_Edit {
            get {
                return ResourceManager.GetString("RibbonContext_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File management.
        /// </summary>
        internal static string RibbonContext_Files {
            get {
                return ResourceManager.GetString("RibbonContext_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Utilities.
        /// </summary>
        internal static string RibbonContext_List {
            get {
                return ResourceManager.GetString("RibbonContext_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        internal static string RibbonContext_View {
            get {
                return ResourceManager.GetString("RibbonContext_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        internal static string RibbonGroup_Clipboard {
            get {
                return ResourceManager.GetString("RibbonGroup_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string RibbonGroup_Code {
            get {
                return ResourceManager.GetString("RibbonGroup_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string RibbonGroup_SaveOpen {
            get {
                return ResourceManager.GetString("RibbonGroup_SaveOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search &amp; Replace.
        /// </summary>
        internal static string RibbonGroup_Search {
            get {
                return ResourceManager.GetString("RibbonGroup_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo &amp; Redo.
        /// </summary>
        internal static string RibbonGroup_UndoRedo {
            get {
                return ResourceManager.GetString("RibbonGroup_UndoRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string RibbonGroup_View {
            get {
                return ResourceManager.GetString("RibbonGroup_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to running service: {0}....
        /// </summary>
        internal static string ServiceInfo {
            get {
                return ResourceManager.GetString("ServiceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code font:.
        /// </summary>
        internal static string SP_CodeFont {
            get {
                return ResourceManager.GetString("SP_CodeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code font size:.
        /// </summary>
        internal static string SP_CodeFontSize {
            get {
                return ResourceManager.GetString("SP_CodeFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to install COM support.
        /// </summary>
        internal static string SP_InstallCOM {
            get {
                return ResourceManager.GetString("SP_InstallCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to install file extensions.
        /// </summary>
        internal static string SP_InstallExt {
            get {
                return ResourceManager.GetString("SP_InstallExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string SP_Language {
            get {
                return ResourceManager.GetString("SP_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable updates.
        /// </summary>
        internal static string SP_Update {
            get {
                return ResourceManager.GetString("SP_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find next.
        /// </summary>
        internal static string SR_FindNext {
            get {
                return ResourceManager.GetString("SR_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to match case.
        /// </summary>
        internal static string SR_MatchCase {
            get {
                return ResourceManager.GetString("SR_MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to match whole word only.
        /// </summary>
        internal static string SR_MatchWholeWord {
            get {
                return ResourceManager.GetString("SR_MatchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace all.
        /// </summary>
        internal static string SR_ReplaceAll {
            get {
                return ResourceManager.GetString("SR_ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace by:.
        /// </summary>
        internal static string SR_ReplaceBy {
            get {
                return ResourceManager.GetString("SR_ReplaceBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search for:.
        /// </summary>
        internal static string SR_SearchFor {
            get {
                return ResourceManager.GetString("SR_SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search &amp; replace.
        /// </summary>
        internal static string SR_Title {
            get {
                return ResourceManager.GetString("SR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrap around.
        /// </summary>
        internal static string SR_WrapAround {
            get {
                return ResourceManager.GetString("SR_WrapAround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC - Closing opened files....
        /// </summary>
        internal static string Status_ClosingFiles {
            get {
                return ResourceManager.GetString("Status_ClosingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC - Creating new metadata....
        /// </summary>
        internal static string Status_CreateMeta {
            get {
                return ResourceManager.GetString("Status_CreateMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC - Creating a file....
        /// </summary>
        internal static string Status_CreatingFile {
            get {
                return ResourceManager.GetString("Status_CreatingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC - Creating reference....
        /// </summary>
        internal static string Status_CreatingReference {
            get {
                return ResourceManager.GetString("Status_CreatingReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC - Deleting resources....
        /// </summary>
        internal static string Status_DeleteResource {
            get {
                return ResourceManager.GetString("Status_DeleteResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC - Installing plugins....
        /// </summary>
        internal static string Status_InstallPlugin {
            get {
                return ResourceManager.GetString("Status_InstallPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC - Moving resource....
        /// </summary>
        internal static string Status_Move {
            get {
                return ResourceManager.GetString("Status_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC - Opening file....
        /// </summary>
        internal static string Status_OpeningFile {
            get {
                return ResourceManager.GetString("Status_OpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a child resource.
        /// </summary>
        internal static string View_AddChild {
            get {
                return ResourceManager.GetString("View_AddChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string View_Copy {
            get {
                return ResourceManager.GetString("View_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string View_Delete {
            get {
                return ResourceManager.GetString("View_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string View_Edit {
            get {
                return ResourceManager.GetString("View_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string View_Move {
            get {
                return ResourceManager.GetString("View_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a new resource.
        /// </summary>
        internal static string WP_CreateResource {
            get {
                return ResourceManager.GetString("WP_CreateResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to resource list.
        /// </summary>
        internal static string WP_GoList {
            get {
                return ResourceManager.GetString("WP_GoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view plugins.
        /// </summary>
        internal static string WP_GoPlugins {
            get {
                return ResourceManager.GetString("WP_GoPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change the configuration.
        /// </summary>
        internal static string WP_GoSettings {
            get {
                return ResourceManager.GetString("WP_GoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you want to start?.
        /// </summary>
        internal static string WP_StartSelection {
            get {
                return ResourceManager.GetString("WP_StartSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string WP_Welcome {
            get {
                return ResourceManager.GetString("WP_Welcome", resourceCulture);
            }
        }
    }
}
