//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.235
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChameleonCoder.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChameleonCoder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string Action_Exit {
            get {
                return ResourceManager.GetString("Action_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart ähnelt.
        /// </summary>
        internal static string Action_Restart {
            get {
                return ResourceManager.GetString("Action_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete the {0}-resource and all its child resources? ähnelt.
        /// </summary>
        internal static string Del_Confirm {
            get {
                return ResourceManager.GetString("Del_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CC resource map ähnelt.
        /// </summary>
        internal static string Ext_CCM {
            get {
                return ResourceManager.GetString("Ext_CCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CC resource package ähnelt.
        /// </summary>
        internal static string Ext_CCP {
            get {
                return ResourceManager.GetString("Ext_CCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CC resource file ähnelt.
        /// </summary>
        internal static string Ext_CCR {
            get {
                return ResourceManager.GetString("Ext_CCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        internal static string Item_Home {
            get {
                return ResourceManager.GetString("Item_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resources ähnelt.
        /// </summary>
        internal static string Item_List {
            get {
                return ResourceManager.GetString("Item_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} [editing] ähnelt.
        /// </summary>
        internal static string Item_ResourceEdit {
            get {
                return ResourceManager.GetString("Item_ResourceEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ähnelt.
        /// </summary>
        internal static string Item_ResourceView {
            get {
                return ResourceManager.GetString("Item_ResourceView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Item_Settings {
            get {
                return ResourceManager.GetString("Item_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} module (version {1}) by {2} ähnelt.
        /// </summary>
        internal static string ModuleInfo {
            get {
                return ResourceManager.GetString("ModuleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description: ähnelt.
        /// </summary>
        internal static string Name_Description {
            get {
                return ResourceManager.GetString("Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string Name_Name {
            get {
                return ResourceManager.GetString("Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resources were successfully packaged! ähnelt.
        /// </summary>
        internal static string Pack_Finished {
            get {
                return ResourceManager.GetString("Pack_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to include the file system equivalents for the packaged resources? ähnelt.
        /// </summary>
        internal static string Pack_IncludeFS {
            get {
                return ResourceManager.GetString("Pack_IncludeFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to include the target resources for the packaged resources? ähnelt.
        /// </summary>
        internal static string Pack_IncludeResolve {
            get {
                return ResourceManager.GetString("Pack_IncludeResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import a resource ähnelt.
        /// </summary>
        internal static string ResourceImport {
            get {
                return ResourceManager.GetString("ResourceImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Package a resource ähnelt.
        /// </summary>
        internal static string ResourcePackage {
            get {
                return ResourceManager.GetString("ResourcePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unpackage resources ähnelt.
        /// </summary>
        internal static string ResourceUnpackage {
            get {
                return ResourceManager.GetString("ResourceUnpackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die create a new resource ähnelt.
        /// </summary>
        internal static string Selection_CreateNew {
            get {
                return ResourceManager.GetString("Selection_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die go to resource list ähnelt.
        /// </summary>
        internal static string Selection_List {
            get {
                return ResourceManager.GetString("Selection_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die change the configuration ähnelt.
        /// </summary>
        internal static string Selection_Settings {
            get {
                return ResourceManager.GetString("Selection_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die running service: {0}... ähnelt.
        /// </summary>
        internal static string ServiceInfo {
            get {
                return ResourceManager.GetString("ServiceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Services ähnelt.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable updates ähnelt.
        /// </summary>
        internal static string Setting_EnableUpdate {
            get {
                return ResourceManager.GetString("Setting_EnableUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die install COM support ähnelt.
        /// </summary>
        internal static string Setting_InstallCOM {
            get {
                return ResourceManager.GetString("Setting_InstallCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die install file extensions ähnelt.
        /// </summary>
        internal static string Setting_InstallExt {
            get {
                return ResourceManager.GetString("Setting_InstallExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language: ähnelt.
        /// </summary>
        internal static string Setting_Language {
            get {
                return ResourceManager.GetString("Setting_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programming directory: ähnelt.
        /// </summary>
        internal static string Setting_ProgrammingDir {
            get {
                return ResourceManager.GetString("Setting_ProgrammingDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die select directory ähnelt.
        /// </summary>
        internal static string Setting_SelectProgDir {
            get {
                return ResourceManager.GetString("Setting_SelectProgDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How do you want to start? ähnelt.
        /// </summary>
        internal static string StartSelection {
            get {
                return ResourceManager.GetString("StartSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CC - deleting resources... ähnelt.
        /// </summary>
        internal static string Status_DeleteResource {
            get {
                return ResourceManager.GetString("Status_DeleteResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CC - packaging resources... ähnelt.
        /// </summary>
        internal static string Status_Pack {
            get {
                return ResourceManager.GetString("Status_Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome! ähnelt.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
